"""
Uvicorn logging configuration reference for PKI Management System.

ACTUAL LOGGING CONFIGURATION:
This module is kept for reference and documentation purposes only.
The actual logging is configured in app.py via the Python API:

    from logging_config import get_uvicorn_log_config
    uvicorn.run(app, log_config=get_uvicorn_log_config(), ...)

WHY NOT --log-config FLAG:
The CLI flag --log-config expects INI/YAML files, not Python modules.
Using the Python API (uvicorn.run parameter) is cleaner and more flexible.

REFERENCE CONFIGURATION:
Below is the structure used by logging_config.get_uvicorn_log_config(),
provided here as documentation for understanding the logging setup.
"""

import os
from logging_config import ISO8601Formatter

# This dictionary is generated by logging_config.get_uvicorn_log_config()
# Shown here as reference documentation only.
_REFERENCE_CONFIG = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "iso8601": {
            "()": ISO8601Formatter,
        },
    },
    "handlers": {
        "default": {
            "formatter": "iso8601",
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stderr",
        },
        "access": {
            "formatter": "iso8601",
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
        },
    },
    "loggers": {
        "uvicorn": {"handlers": ["default"], "level": os.environ.get("PKI_LOG_LEVEL", "INFO").upper()},
        "uvicorn.access": {"handlers": ["access"], "level": os.environ.get("PKI_LOG_LEVEL", "INFO").upper(), "propagate": False},
        "uvicorn.error": {"handlers": ["default"], "level": os.environ.get("PKI_LOG_LEVEL", "INFO").upper()},
    },
}
